<?php
return [
    1 => [
        'Administrator',
        'Manage Users',
        'Gii',
        'Ajax Requests',
        'Language',
        'Front House check List',
        'Production Area',
        'Hair & Mackup Checklist',
        'Salon Area Checklist',
        'Spa checklist',
        'Manicure Checklist',
        'Common area checklist',
        'Customers Health',
        'Customers Acrylic',
        'Customers Body Scrub',
        'Customers Facial',
        'Customers Keratin',
        'Customers Manicur',
        'Customers massage',
        'Customers Visits',
        'Customers Hair Treatment',
        'Customers Hair Colour',
        'Customers Visits',
        'Branches',
    ],
    3 => [
        'Customers Manicur',
    ],
    50 => [
        'Therapist',
    ],
];
